apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
     - name: noise
       image: 0latency/noise:latest
       env:
       - name: TH 
         value: "500"
  priorityClassName: system-node-critical
